main = do print (pi :: Float)
          print (exp 1 :: Float)
          print (log 10 :: Float)
          print (sqrt 2 :: Float)
          print (pi ** 2 :: Float)
          print (logBase 2 10 :: Float)
          print (sin 1 :: Float)
          print (cos 1 :: Float)
          print (tan 1 :: Float)
          print (asin (-1) :: Float)
          print (acos (-1) :: Float)
          print (atan 1 :: Float)
          print (sinh 1 :: Float)
          print (cosh 1 :: Float)
          print (tanh 1 :: Float)
          print (asinh 1 :: Float)
          print (acosh 2 :: Float)
          print (atanh 0.5 :: Float)

