main = do print $ properFraction (3.14 :: Float)
          print $ truncate (1.7 :: Float)
          print $ truncate (-1.7 :: Float)
          print $ round (3.4 :: Float)
          print $ round (3.6 :: Float)
          print $ round (-3.6 :: Float)
          print $ ceiling (3.7 :: Float)
          print $ ceiling (-4.999 :: Float)
          print $ floor (3.001 :: Float)
          print $ floor (-4.999 :: Float)
