#!/bin/bash

s=$1
bname=`basename $s .hs`

echo "# 1. tcompile"
./tcompile.sh $s
if [ $? -ne 0 ];then
  exit 1
fi

cd jout

echo "# 2. jout/compile"
./compile $bname/Sample.java
if [ $? -ne 0 ];then
  exit 1
fi

echo "# 3. jout/run"
./run $bname/Sample.java
exit $?

