#!/bin/bash

target=$1
d=`dirname $1`
c=`basename $1 .java`

s=":"
if [ -d /c ]; then
    s=";"
fi

java -Dfile.encoding=UTF-8 -ea -cp "../../brt/src$s$d" $c
if [ $? -ne 0 ];then
    echo "abend!"
    exit 1
fi
