#!/bin/bash

target=$1
d=`dirname $1`
c=`basename $1 .java`

s=":"
if [ -d /c ]; then
    s=";"
fi

java -Duser.language=en -Dfile.encoding=UTF-8 -ea -cp "../../brt/src$s$d" $c 2> trace.txt
if [ $? -ne 0 ];then
    tail trace.txt
    exit 1
fi
